config/routes.rb
Flipbook::Application.routes.draw do

   resources :users, :flipbks, :logins, :photos
   
   get 'profile/:id' => 'public#profile', :as => :profile
   
   get 'flipbks/delete/:id' => 'flipbks#destroy'
   match 'users/:id' => 'users#show'
   
   # To visualize grid structure.
   get '/grid/' => 'public#grid'
   
   root :to => 'public#index'

end


       

app/models/flipbk.rb
class Flipbk < ActiveRecord::Base
  attr_accessible :description, :name, :user_id, :speed, :public, :photo_id, :display, :order
                 
  belongs_to :user
  has_many :photos
  
  # def save_to_s3(dir, name)
#     service = S3::Service.new(
#       :access_key_id     => ENV['AWS_ACCESS_KEY_ID'], 
#       :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
#     )
#     
#     speed = self.speed / 10
#     system("convert -delay #{speed} #{dir}*.png #{dir}#{name}.gif")
#     
#     # dir/flipbook.gif to amazon s3 and then save public url to flipbk
#     
#     bucket = service.buckets.find("flipbookv2")
# 
#     new_object = bucket.objects.build("#{name}.gif")
# 
#     new_object.content = open("#{dir}#{name}.gif")
# 
#     new_object.save
#     
#     object = bucket.objects.find("#{name}.gif")
#     @book.url = object.url
# 
#     @book.save  
#   end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :flipbk_id, :photo, :user_id, :order
  
  mount_uploader :photo, PhotoUploader
  
  belongs_to :flipbk
  belongs_to :user
  
  validates_uniqueness_of :photo

end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation
  validates :email, :name, :password, :password_confirmation, presence: true
  validates :email, :uniqueness => true, email: true
  validates :password, length: { minimum: 6 }
  
  has_many :flipbks
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  RAILS_ROOT = "." || RAILS_ROOT
  
  def authorize
    if current_user.nil?
      redirect_to :new_login
    end
  end
  
  private
  
  # Return either `nil` or a User object.
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  
  helper_method :current_user
  
  def destroy
    session[:user_id] = nil
    redirect_to(:root)
  end
  
end

app/controllers/dropbox_controller.rb
require 'dropbox_sdk'

class DropboxController < ApplicationController
    
  def client_chk
    client = get_dropbox_client
    unless client
      redirect_to(:action => 'auth_start') and return
    end
    
    account_info = client.account_info
  end
  
  def get_dropbox_client
    if session[:access_token]
      begin
          access_token = session[:access_token]
          DropboxClient.new(access_token)
      end
    end
  end

  def get_web_auth()
    redirect_uri = url_for(:action => 'auth_finish')
    DropboxOAuth2Flow.new(ENV["DROPBOX_APP_KEY"], ENV["DROPBOX_APP_SECRET"], redirect_uri, session, :dropbox_auth_csrf_token)
  end

  def auth_start
    authorize_url = get_web_auth().start()

    # Send the user to the Dropbox website so they can authorize app. After the user
    # authorizes app, Dropbox will redirect them here with a 'code' parameter.
    redirect_to authorize_url
  end

  def auth_finish
    @book = Flipbk.find(params[:id])
    begin
        access_token, user_id, url_state = get_web_auth.finish(params)
        session[:access_token] = access_token
        flash[:success] = "You have successfully linked to dropbox."
        redirect_to(edit_flipbk_path(@book.id))
    end
  end

end

app/controllers/flipbks_controller.rb
class FlipbksController < ApplicationController
  
  def index
    @user = User.find(session[:user_id])
  end
  
  def show
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
    
    @book = Flipbk.find(params[:id])
    
    if @book.public?
      
    else
      if current_user && @book.user.id == current_user.id
      else
      redirect_to(:root)
      end
    end
  end
  
  def new
    @user = User.find(session[:user_id])
    @book = Flipbk.new
  end

  def create
    @user = User.find(session[:user_id])
    @book = Flipbk.new(params[:flipbk])
    @book.user_id = session[:user_id]
    
    @book.save
    redirect_to(user_path(@user.id))
  end
  
  def edit
    @user = User.find(session[:user_id])
    @book = Flipbk.find(params[:id])
    @photos = Photo.where(params[:flipbk_id])
  end

  def update
    @user = User.find(session[:user_id])
    @book = Flipbk.find(params[:id])
    @book.update_attributes(params[:flipbk])
    @book.user_id = session[:user_id]
    
    redirect_to(user_url_path(@user.id))
  end
    
  def destroy
    book = Flipbk.find(params[:id])
    
    book.photos.each do |p|
    p.flipbk_id = nil
    end
    
    book.delete
    redirect_to(:users)
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by_email(params[:email])
    
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_url(@user.id)
    else
      render "new"
    end
  end
  
  def destroy
    authorize
    session[:user_id] = nil
    redirect_to(:root)
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def new
    @user = User.find(session[:user_id])
    @book = Flipbk.where(:flipbk_id => params[:flipbk_id])
    @photo = Photo.new   
  end
  
  def create
    @user = User.find(session[:user_id])
    @photo = Photo.new(:photo => params[:photo])
    
    @photo.flipbk_id = @book.id
    @photo.user_id = session[:user_id] 
    
    @book.update_attributes(:photo_id => @photo.id)
    
    @photo.save
    redirect_to(user_path(@user.id))
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
end



   

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
    @users = User.all
    @user = User.new
    @public_flipbks = []
    
    Flipbk.all.each do |f|
      if f.public
        @public_flipbks << f
      end
    end
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to(:user)
    else
      render "new"
    end
  end

  def profile
    if session[:user_id] 
      @user = User.find(params[:id])
    else
      redirect_to :root
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    if current_user
      redirect_to(user_url(current_user.id))
    end
  end
  
  def new
     @user = User.new
  end

  def create
   @user = User.new(params[:user])

   if @user.save
     session[:user_id] = @user.id
  
     redirect_to(user_url(current_user.id))
   else
     render "new"
   end
  end
  
  def show
    @user = User.find(session[:user_id])
    @book = Flipbk.new
    @books = Flipbk.all
    
    if params[:id].to_s == session[:user_id].to_s
    else
      redirect_to profile_url params[:id].to_i
    end 
  end
  
  def edit
    @user = User.find(session[:user_id])
  end

  def update
    redirect_to(user_url(current_user.id))
  end
  
  def destroy
    redirect_to(:root)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flipbks/_form.html.erb
<div id="flipbook_all">
  <%= form_for book do |f| %>
    <div id="flipbook_form" class="grid_12 alpha omega">
    
      <ul>
        <%= f.hidden_field :user_id %>

        <li>
          <%= f.text_field :name, :placeholder => "Name" %>
        </li>
  
        <li>
          <%= f.text_field :description, :placeholder => "Describe" %>
        </li>
  
        <li>
          <% spd = book.speed || 200 %>
          <%= f.text_field :speed , :placeholder => "How fast? (200)" %>
        </li>
  
        <li>
          <%= f.label "Make public?" %>
          <%= f.check_box :public %>
        </li>
        
        <% if (params[:action] == 'edit') %>
          <div id="main_button" class="grid_12 alpha omega">
            <%= f.submit "Save flipbook", :controller => :flipbks, :action => :show, :class => "ctr_button" %>
          </div>
        <% else %>
          <div id="main_button" class="grid_12 alpha omega">
            <%= f.submit "Start a flipbook", :controller => :flipbks, :action => :create, :class => "ctr_button" %>
          </div> 
        <% end %>
      
      </ul>
    </div>
  <% end %> 
</div>
  

  
  
  <!-- contents, metadata = client.get_file_and_metadata('/magnum-opus.txt')
  open('magnum-opus.txt', 'w') {|f| f.puts contents }
  
  # Upload the POST'd file to Dropbox, keeping the same name
              resp = client.put_file(params[:file].original_filename, params[:file].read)
              render :text => "Upload successful.  File now at #{resp['path']}"
    <%= button_to "Add Photo", user_url(current_user.id), :method => :get, :class => "ctr_button" %>
  
  
  
  
  <! <div id="insta_photos" class="grid_12 alpha omega">
    <div id="photos">
      <% User.find(session[:user_id]).photos.all.each do |p| %>
        <div id="photos_new">
          <label for="<%= p.id %>">
            <%= image_tag(p.url, height: '140', width: '140') %>

            <%= check_box_tag('photos[]', p.id, (((p.flipbk_id == book.id)&& p.flipbk_id != nil)? true : false), :id => "#{p.id}" ) %>

            <% p.order = p.order || 0 %>
            
          </label>
        </div>
      <% end %>
    </div>
  </div>
   -->

  




     

app/views/flipbks/edit.html.erb
<!DOCTYPE html>
<html>
<body>

<div id="container" class="container_12">
  
  <div id="profile_banner" class="grid_12 alpha omega">
      <div id="name" class="center">
        <%= current_user.name %>
      </div>
      
      <div class="separator"></div>
      
      <div id="tagline" class="center">
        share what you make
      </div>
      
      <div id="flipbook">
        <%= render partial: "form", locals: {book: @book, user: @user} %>
      </div>
  </div>
  
  <div id="buffer2" class="grid_12 alpha omega">
      <% if @photos == true %>
        <div id="buff_text2">
          FLIPBOOK PHOTOS
        </div>
      <% else %>
        <div id="buff_text2">
          Add photos to <%= @book.name %>
        </div>
      <% end %>
  </div>
  
  <div id="uploader" class="grid_12 alpha omega">
    
    <!-- <% if @client == true %>
    You are linked to Dropbox!
    <% else %>
    <%= button_to "Connect to Dropbox", :dbcheck, :method => :get, :class => "ctr_button" %>
    <% end %>
    
    <%= render partial: "photos/form", locals: {book: @book, user: @user} %> -->
    
  </div>
  
  <div class="clear"></div>
  
  <div id="dropbox_photos" class="grid_12 alpha omega">
   
    Render all photos here.
   
  </div>
  
  <div class="push"></div>
        
</div>

</body>
</html>

app/views/flipbks/index.html.erb
<body>
  <div id="fb_main">
    <h2>Your flipbooks</h2>
    <div id="flipbook_index">
  
      <div id="flipbook_index_list">
        <% @user.flipbks.each do |book| %>
      <p>
        <% book.delete if book.photos.all.empty? %>
        <%=  link_to(image_tag(book.photos.all.first.photo_url,:alt => book.name, :size => "120x120"), flipbk_path(book.id)) if !(book.photos.all.empty?) %>
      </p>
        <% end %>
      </div>
      <div id="link_new_flipbook">
        <%= link_to('Create flipbook', '/flipbks/new') %>
      </div>
    </div>
  </div>
</body>

app/views/flipbks/new.html.erb
<!DOCTYPE html>
<html>
<body>

<div id="container" class="container_12">
  
  <div id="profile_banner" class="grid_12 alpha omega">
      <div id="name" class="center">
        <%= current_user.name %>
      </div>
      
      <div class="separator"></div>
      
      <div id="tagline" class="center">
        share what you make
      </div>
      
      <div id="fb_menu">
        
        <%= button_to "Your flipbooks", user_url(current_user.id), :method => :get, :class => "ctr_button" %>
                    
      </div>
  </div>
  
  <div id="flipbook">
    <%= render partial: "form", locals: {book: @book} %>
  </div>
  
  <div class="push"></div>
        
</div>

</body>
</html>

app/views/flipbks/show.html.erb
<!DOCTYPE html>
<html>
<body>

<div id="container" class="container_12">
  
  <div id="nav2" class="grid_12 alpha omega">
  
      <div id="fb_topbar" class"grid_6">
        <ul id="settings">
          <% if current_user && current_user.id == @book.user_id %>
  
          <li><%= button_to "Edit", "/flipbks/#{@book.id}/edit", :method => :get, :class => "fb_button" %></li>

          <li><%= button_to "Delete", flipbk_path("delete/#{@book.id}"), method: :delete, :class => "fb_button" %></li>

          <% else %>

          <% end %>
        </ul>
      </div>
  </div>
  
  <div id="flipbook_sq" class="grid_12 alpha omega">
    <div id="flipbook_back" class="grid_6 push_3">
      
      
      <div class="grid_12 alpha omega">
      <div id="name" class="center">
        <%= @book.name %>
      </div>
      
      <div class="separator"></div>
      
      <div id="tagline" class="center">
        <%= @book.description %>
      </div>
      
      <div id="fb_show">

        <%= image_tag(@book.flipbk_url, height: '450', width: '450') %>
        
      </div>
  </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<script src="http://platform.tumblr.com/v1/share.js"></script>

<head>
  <title>flipbook</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,200,900' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<!-- Facebook integration. -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{1492301310990221}',
      status     : true,
      xfbml      : true
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<!-- Twitter integration. -->
<script>
  $('.popup').click(function(event) {
    var width  = 575,
        height = 400,
        left   = ($(window).width()  - width)  / 2,
        top    = ($(window).height() - height) / 2,
        url    = this.href,
        opts   = 'status=1' +
                 ',width='  + width  +
                 ',height=' + height +
                 ',top='    + top    +
                 ',left='   + left;

    window.open(url, 'twitter', opts);

    return false;
  });
</script>

</head>

<body>
 
<% if current_user %>
   <div id="navbar" class="container_12"> 
      <div id="nav" class="grid_12 alpha omega">
          <div id="social" class="grid_4 alpha">
              <div id="flip_icon">
                <%= link_to :root do %>
                  <%= image_tag "flipbook60.jpg" %>
                <% end %>
              </div>

              <div id="avatar">
                <%= gravatar_tag User.find(session[:user_id]), :size => 60 %>
              </div>  
          </div>
    
          <div id="links" class="grid_4 omega push_4">
              <%= link_to("Log Out", login_path(session[:user_id]), :method => :delete) %>
              <%= link_to("Profile", user_url(current_user.id)) %> 
          </div>
      </div>
  </div>
<% end %>

<div>
  
  <%= yield %> 
  
</div>

<% if current_user %>
  <footer class="container_12">
    
    <div id="footer" class="grid_12 alpha omega">
      
        <div id="foot_signup">
        
          <div id="foot_links" class="grid_4 push_8">
            <div class="foot_buttons">
              <div id="fb-root"></div>
              <div id="social_icon3">
                <a href="#" class="tumblr_icon"></a>
              </div>
              <div id="social_icon2">
                <a href="#" class="twitter_icon"></a>
              </div>
              <div id="social_icon1">
                <a href="#" class="facebook_icon"></a>
              </div>
        
              <div id="flip_icon">
                <%= link_to :root do %>
                  <%= image_tag "flipbook60.jpg" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      
        <div id="credits" class="grid_12 alpha omega">
          © 2014 flipbook, Inc. • Proudly built on the Silicon Prairie • Terms of service • Privacy Policy
        </div>
    </div>  
  </footer>
<% end %>

</body> 

</html>

app/views/logins/new.html.erb
<!DOCTYPE html>
<html>
<body>
  
<div id="container" class="container_12">

  <div id="login_nav" class="grid_12 alpha omega">
      <div id="social" class="grid_4 alpha">
          <div id="flip_icon">
            <%= link_to :root do %>
              <%= image_tag "flipbook60.jpg" %>
            <% end %>
          </div>
      </div>
  </div>

  <div id="login_banner" class="grid_12 alpha omega">
    <div id="name_blk" class="grid_4 push_4">
      <div id="name" class="center">
        <span>flip</span>book
      </div>

      <div class="separator"></div>
    </div>
  
    <div class="clear"></div>

    <div id="login_form" class="grid_4 push_4">
    
        <!-- <% if @user %>
         Username or password incorrect
        <% end %> -->
      
        <%= form_tag logins_path do |f| %>

        <div id="email">
          <%= text_field_tag :email, nil, placeholder: "Email" %>
        </div>

        <div id-"password">
          <%= password_field_tag :password, nil, placeholder: "Password" %>
        </div>
      
        <div id="login">
          <%= submit_tag "Log In", :class => 'ctr_button' %>
        </div>
        <% end %>
   
    </div>
  </div>

</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_tag({:action => :create}, :multipart => true) do %>
  <%= file_field_tag :photo %>
  <%= submit_tag 'Download' %>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

app/views/photos/new.html.erb
<%= render 'form' %>

app/views/photos/show.html.erb
<h1><%= @photo.name %></h1>

<p><%= image_tag @photo.photo.url %></p>

<p>
  <%= link_to "Edit", edit_photo_path(@photo) %> |
  <%= link_to "Destroy", @photo, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Photos", photos_path %>
</p>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<body>

<div id="container" class="container_12">
  
  <div id="profile_banner" class="grid_12 alpha omega">
      <div id="name" class="center">
        <%= current_user.name %>
      </div>
      
      <div class="separator"></div>
      
      <div id="tagline" class="center">
        share what you make
      </div>
      
      <div id="flipbook">
        <%= render partial: "flipbks/form", locals: {book: @book, user: @user} %>
      </div>
  </div>
  
  <div id="buffer2" class="grid_12 alpha omega">
      <% if !@user.flipbks.all.empty? %>
        <div id="buff_text2">
          YOUR FLIPBOOKS
        </div>
      <% else %>
        <div id="buff_text2">
          YOU NEED SOME FLIPBOOKS
        </div>
      <% end %>
  </div>
  
  <div id="profile_flipbooks" class="grid_12 alpha omega">
    
      <div id="fbs_all">
        <ul>
          <% @user.flipbks.each do |book| %>
        <li>
          <% if book.photos.all.empty? %>
            <%= link_to flipbk_path(book.id) do %>
              <%= image_tag "placeholder.jpg" %>
            <% end %>
          <% else %>
            <%= link_to flipbk_path(book.id) do %>
              <%= image_tag book.photos.all.first.url %>
            <% end %>
          <% end %>
        </li>
          <% end %>
        </ul>
      </div>
  </div>
  
  <div class="push"></div>
      
</div>

</body>
</html>